source /usr/share/antigen.zsh

antigen use oh-my-zsh # ugh

antigen bundle git
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting

# theme from oh-my-zsh
antigen bundle ys
antigen theme ys

antigen apply

# Paths
export GOPATH="$HOME/gocode"
export PATH="$PATH:$HOME/.npm-packages/bin:$HOME/gocode/bin:$HOME/bin"
export PATH="$PATH:$HOME/.dotnet/tools"
export VISUAL=nvim

# Vim mode
bindkey -v
export KEYTIMEOUT=1
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

# Start direnv
eval "$(direnv hook zsh)"

# Start pyenv
export PATH="/home/dave/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Inject kubectl completions
source <(kubectl completion zsh)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
